//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajHakathon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNameResourses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNameResourses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HajHakathon.Resources.DisplayNameResourses", typeof(DisplayNameResourses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna Location.
        /// </summary>
        public static string AntennaLocation {
            get {
                return ResourceManager.GetString("AntennaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna Name.
        /// </summary>
        public static string AntennaName {
            get {
                return ResourceManager.GetString("AntennaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna No.
        /// </summary>
        public static string AntennaNo {
            get {
                return ResourceManager.GetString("AntennaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string AttachmentID {
            get {
                return ResourceManager.GetString("AttachmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Item.
        /// </summary>
        public static string AttachmentItemID {
            get {
                return ResourceManager.GetString("AttachmentItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Item.
        /// </summary>
        public static string AttachmentItemName {
            get {
                return ResourceManager.GetString("AttachmentItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Title.
        /// </summary>
        public static string AttachmentTitle {
            get {
                return ResourceManager.GetString("AttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Url.
        /// </summary>
        public static string AttachmentUrl {
            get {
                return ResourceManager.GetString("AttachmentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string CompanyID {
            get {
                return ResourceManager.GetString("CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo.
        /// </summary>
        public static string CompanyLogoUrtl {
            get {
                return ResourceManager.GetString("CompanyLogoUrtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Company.
        /// </summary>
        public static string DealerCompanyName {
            get {
                return ResourceManager.GetString("DealerCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device BarCode.
        /// </summary>
        public static string DeviceBarCode {
            get {
                return ResourceManager.GetString("DeviceBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceID.
        /// </summary>
        public static string DeviceID {
            get {
                return ResourceManager.GetString("DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Image.
        /// </summary>
        public static string DeviceImageUrl {
            get {
                return ResourceManager.GetString("DeviceImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Item.
        /// </summary>
        public static string DeviceItemID {
            get {
                return ResourceManager.GetString("DeviceItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Item.
        /// </summary>
        public static string DeviceItemName {
            get {
                return ResourceManager.GetString("DeviceItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Resualt.
        /// </summary>
        public static string DeviceMaintenanceResualtID {
            get {
                return ResourceManager.GetString("DeviceMaintenanceResualtID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requairment Examination in Device.
        /// </summary>
        public static string DeviceRequairmentMaintenance {
            get {
                return ResourceManager.GetString("DeviceRequairmentMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requairment Examination in Device.
        /// </summary>
        public static string DeviceRequairmentMaintenanceID {
            get {
                return ResourceManager.GetString("DeviceRequairmentMaintenanceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Statues.
        /// </summary>
        public static string DeviceStatuesID {
            get {
                return ResourceManager.GetString("DeviceStatuesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Statues ID 1.
        /// </summary>
        public static string DeviceStatuesID1 {
            get {
                return ResourceManager.GetString("DeviceStatuesID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Statues.
        /// </summary>
        public static string DeviceStatuesName {
            get {
                return ResourceManager.GetString("DeviceStatuesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAdress {
            get {
                return ResourceManager.GetString("EmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Name.
        /// </summary>
        public static string EmpDoMaintenance {
            get {
                return ResourceManager.GetString("EmpDoMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genral Maintenance Resualt.
        /// </summary>
        public static string EndMaintenanceResualt {
            get {
                return ResourceManager.GetString("EndMaintenanceResualt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC.
        /// </summary>
        public static string EPC {
            get {
                return ResourceManager.GetString("EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Periodic Maintenance Date.
        /// </summary>
        public static string FirstPeriodicMaintenanceDate {
            get {
                return ResourceManager.GetString("FirstPeriodicMaintenanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request End Date.
        /// </summary>
        public static string MaintenanceEndRequestDate {
            get {
                return ResourceManager.GetString("MaintenanceEndRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Request.
        /// </summary>
        public static string MaintenanceID {
            get {
                return ResourceManager.GetString("MaintenanceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Item.
        /// </summary>
        public static string MaintenanceItemID {
            get {
                return ResourceManager.GetString("MaintenanceItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Item.
        /// </summary>
        public static string MaintenanceItemName {
            get {
                return ResourceManager.GetString("MaintenanceItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string MaintenanceRequestDate {
            get {
                return ResourceManager.GetString("MaintenanceRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Request No.
        /// </summary>
        public static string MaintenanceRequestNumber {
            get {
                return ResourceManager.GetString("MaintenanceRequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manfacture.
        /// </summary>
        public static string Manfacture {
            get {
                return ResourceManager.GetString("Manfacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationaID {
            get {
                return ResourceManager.GetString("NationaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Maintenance From PPM.
        /// </summary>
        public static string NeedMaintenanceFromPPM {
            get {
                return ResourceManager.GetString("NeedMaintenanceFromPPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Maintenance.
        /// </summary>
        public static string PeriodicMaintenance {
            get {
                return ResourceManager.GetString("PeriodicMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Maintenance After Days.
        /// </summary>
        public static string PeriodicMaintenanceAfterDays {
            get {
                return ResourceManager.GetString("PeriodicMaintenanceAfterDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase Date.
        /// </summary>
        public static string purchaseDate {
            get {
                return ResourceManager.GetString("purchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReaderAntennaID.
        /// </summary>
        public static string ReaderAntennaID {
            get {
                return ResourceManager.GetString("ReaderAntennaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance By.
        /// </summary>
        public static string RequestMaintenanceBy {
            get {
                return ResourceManager.GetString("RequestMaintenanceBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination Resault.
        /// </summary>
        public static string ResaultID {
            get {
                return ResourceManager.GetString("ResaultID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination Resault.
        /// </summary>
        public static string ResaultName {
            get {
                return ResourceManager.GetString("ResaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Device ID.
        /// </summary>
        public static string RFIDDeviceID {
            get {
                return ResourceManager.GetString("RFIDDeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Device Name.
        /// </summary>
        public static string RFIDDeviceName {
            get {
                return ResourceManager.GetString("RFIDDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID IP Address.
        /// </summary>
        public static string RFIDIPAddress {
            get {
                return ResourceManager.GetString("RFIDIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string RfidLocationNo {
            get {
                return ResourceManager.GetString("RfidLocationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Device Name.
        /// </summary>
        public static string RFIDTBLID {
            get {
                return ResourceManager.GetString("RFIDTBLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialNumber.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Sender Email.
        /// </summary>
        public static string SystemEmailSender {
            get {
                return ResourceManager.GetString("SystemEmailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SystemEmailSenderPassword {
            get {
                return ResourceManager.GetString("SystemEmailSenderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Sender Email SMTP.
        /// </summary>
        public static string SystemEmailSenderSMTP {
            get {
                return ResourceManager.GetString("SystemEmailSenderSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Image.
        /// </summary>
        public static string UserAvatarUrl {
            get {
                return ResourceManager.GetString("UserAvatarUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User State.
        /// </summary>
        public static string UserState {
            get {
                return ResourceManager.GetString("UserState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User State.
        /// </summary>
        public static string UserStateID {
            get {
                return ResourceManager.GetString("UserStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Expiration Date.
        /// </summary>
        public static string WarrantyExpirationDate {
            get {
                return ResourceManager.GetString("WarrantyExpirationDate", resourceCulture);
            }
        }
    }
}
