//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajHakathon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GbResoures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GbResoures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HajHakathon.Resources.GbResoures", typeof(GbResoures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applecation Settings.
        /// </summary>
        public static string ApplecationSettings {
            get {
                return ResourceManager.GetString("ApplecationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Item Settings.
        /// </summary>
        public static string AttachmentSettings {
            get {
                return ResourceManager.GetString("AttachmentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        public static string Chats {
            get {
                return ResourceManager.GetString("Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices Settings.
        /// </summary>
        public static string CompanyDevicesSettings {
            get {
                return ResourceManager.GetString("CompanyDevicesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string CompanyMedDevicesSettings {
            get {
                return ResourceManager.GetString("CompanyMedDevicesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Profile.
        /// </summary>
        public static string CompanyProfile {
            get {
                return ResourceManager.GetString("CompanyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments settings.
        /// </summary>
        public static string DepartmentsSettings {
            get {
                return ResourceManager.GetString("DepartmentsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Items Settings.
        /// </summary>
        public static string DeviceItemSettings {
            get {
                return ResourceManager.GetString("DeviceItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Statues Settings.
        /// </summary>
        public static string DeviceStatuesSettings {
            get {
                return ResourceManager.GetString("DeviceStatuesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit company info.
        /// </summary>
        public static string EditCompanyinfo {
            get {
                return ResourceManager.GetString("EditCompanyinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejraat.
        /// </summary>
        public static string Ejraatlink {
            get {
                return ResourceManager.GetString("Ejraatlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password ?.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello:.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login System.
        /// </summary>
        public static string LoginSystem {
            get {
                return ResourceManager.GetString("LoginSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string LoginUserName {
            get {
                return ResourceManager.GetString("LoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string MainCourse {
            get {
                return ResourceManager.GetString("MainCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance examination result setting.
        /// </summary>
        public static string MaintenanceExaminationResultSetting {
            get {
                return ResourceManager.GetString("MaintenanceExaminationResultSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance item settings.
        /// </summary>
        public static string MaintenanceItemSettings {
            get {
                return ResourceManager.GetString("MaintenanceItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majal.
        /// </summary>
        public static string Majal {
            get {
                return ResourceManager.GetString("Majal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGES.
        /// </summary>
        public static string MESSAGES {
            get {
                return ResourceManager.GetString("MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moasherat.
        /// </summary>
        public static string Moasheratlink {
            get {
                return ResourceManager.GetString("Moasheratlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Inbox.
        /// </summary>
        public static string MyInbox {
            get {
                return ResourceManager.GetString("MyInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewRecored {
            get {
                return ResourceManager.GetString("NewRecored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read all messages.
        /// </summary>
        public static string ReadAllMessages {
            get {
                return ResourceManager.GetString("ReadAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read all notifications.
        /// </summary>
        public static string ReadAllNotifications {
            get {
                return ResourceManager.GetString("ReadAllNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statues Name.
        /// </summary>
        public static string SchoolStatuesName {
            get {
                return ResourceManager.GetString("SchoolStatuesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to school Year.
        /// </summary>
        public static string schoolYearlink {
            get {
                return ResourceManager.GetString("schoolYearlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;------ Select ------&gt;.
        /// </summary>
        public static string SelectFormComboBox {
            get {
                return ResourceManager.GetString("SelectFormComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Of Moashreat.
        /// </summary>
        public static string SettingOfMoashreat {
            get {
                return ResourceManager.GetString("SettingOfMoashreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labaik Platphorm.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string tableOption {
            get {
                return ResourceManager.GetString("tableOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Mangement.
        /// </summary>
        public static string usersMangments {
            get {
                return ResourceManager.GetString("usersMangments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users mangment.
        /// </summary>
        public static string usersMangmentsSettings {
            get {
                return ResourceManager.GetString("usersMangmentsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User State Settings.
        /// </summary>
        public static string UserStatSettings {
            get {
                return ResourceManager.GetString("UserStatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Web Site.
        /// </summary>
        public static string ViewWebSite {
            get {
                return ResourceManager.GetString("ViewWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waranty is Expired.
        /// </summary>
        public static string WarantyExpairStatText {
            get {
                return ResourceManager.GetString("WarantyExpairStatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waranty is Active.
        /// </summary>
        public static string WarantyNotExpairStatText {
            get {
                return ResourceManager.GetString("WarantyNotExpairStatText", resourceCulture);
            }
        }
    }
}
