//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajHakathon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_Users()
        {
            this.G_AirLineCompany_User = new HashSet<G_AirLineCompany_User>();
            this.G_TawafCompany_User = new HashSet<G_TawafCompany_User>();
        }
    
        public int ID { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public string PassportID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string VisaNumber { get; set; }
        public Nullable<int> BarcodeIQ { get; set; }
        public Nullable<int> AirLinesCompanyID { get; set; }
        public Nullable<int> TawafaCompanyID { get; set; }
        public string Gender { get; set; }
        public string Photo { get; set; }
        public string TouchID { get; set; }
        public string PassportSource { get; set; }
        public Nullable<int> CountaryID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string PortNumber { get; set; }
        public string VisaIssuance { get; set; }
        public Nullable<bool> IsNedded { get; set; }
        public string BlodGroup { get; set; }
        public string MobileNumber { get; set; }
        public string IdentityNumber { get; set; }
        public string TasreeeNumber { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual EPCs EPCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_AirLineCompany_User> G_AirLineCompany_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_TawafCompany_User> G_TawafCompany_User { get; set; }
        public virtual Sys_Countaries Sys_Countaries { get; set; }
        public virtual Sys_Languages Sys_Languages { get; set; }
    }
}
