//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajHakathon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Zone
    {
        public int Id { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> InDeviceID { get; set; }
        public Nullable<int> OutDeviceID { get; set; }
        public Nullable<int> MaxCount { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual Devices Devices1 { get; set; }
        public virtual Sys_Area Sys_Area { get; set; }
    }
}
