//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajHakathon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ChekPoints
    {
        public int ID { get; set; }
        public int AreaID { get; set; }
        public int RFIDDeviceID { get; set; }
        public string chekpointNameAr { get; set; }
        public string chekpointNameEn { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual Sys_Area Sys_Area { get; set; }
    }
}
