//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajHakathon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Area()
        {
            this.Sys_ChekPoints = new HashSet<Sys_ChekPoints>();
            this.Sys_Zone = new HashSet<Sys_Zone>();
        }
    
        public int ID { get; set; }
        public int CityId { get; set; }
        public string AreaNameAr { get; set; }
        public string AreaNameEn { get; set; }
        public int MaxInArea { get; set; }
    
        public virtual Sys_Cities Sys_Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_ChekPoints> Sys_ChekPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Zone> Sys_Zone { get; set; }
    }
}
