//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
namespace HajHakathon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagEvents
    {
        [JsonProperty(PropertyName ="TagEventID")]
        public int ID { get; set; }
        public System.DateTime UtcTimestamp { get; set; }
        public byte TagEventId { get; set; }
        public int ChannelId { get; set; }
        [JsonProperty(PropertyName = "Devices")]
        public Nullable<int> DeviceId { get; set; }
        public Nullable<int> AntennaId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public int EPCId { get; set; }
        public Nullable<int> SerialNumberId { get; set; }
        public Nullable<int> UserMemoryId { get; set; }
        public Nullable<int> DecodeAlgorithmId { get; set; }
        public Nullable<int> DecodedEPCId { get; set; }
        public Nullable<int> DecodedUserMemoryId { get; set; }
        public Nullable<int> DeviceLocationId { get; set; }
        public Nullable<int> AntennaLocationId { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual EPCs EPCs { get; set; }
    }
}
